# Site settings
title: "梓瑶的博客"
logo: logo.JPG # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: zhangziyao@yiyun.com
description: > # this means to ignore newlines until "baseurl:"
    我是梓瑶，今天我的博客正式开业了@2015_12_12
url: "http://ziyao.co" # the base hostname & protocol for your site
twitter_username: zhangziyao
github_username:  zhangziyao

# Build settings
markdown: kramdown
